<?php

// Prepare form
$form = $this->resetPasswordForm;
$redirectUrl = isset($_GET['redirect']) ? $_GET['redirect'] : $this->redirect;
$redirect = $redirectUrl ? '?redirect=' . $redirectUrl : null;
$form->setAttribute('action', $this->url('infinityuser/resetpassword'));
$form->prepare();

// Get elements
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary pull-right');

// Start form
echo $this->form()->openTag($form);
?>
    <h3 class="form-signin-heading">
        Forgotten Password?
    </h3>
    <p>
        Enter you email address here for instructions on how to reset it to be
        sent to you.
    </p>
    <?php
    echo $this->messages();
    foreach ($form as $element) {
        if ($submit != $element) {
            $element->setAttribute('placeholder', $element->getLabel());
            echo $this->formRow($element);
        }
    }
    ?>
    <div class="form-buttons">
        <?php echo $this->formRow($submit) ?>
    </div>
    <div class="form-links">
        <a href="<?php echo $this->url('zfcuser/register') . $redirect ?>">Register</a>
        | Already registered?
        <a href="<?php echo $this->url('zfcuser/login') . $redirect ?>">Login</a> here.
    </div>
<?php
// End form
echo $this->form()->closeTag()
?>