<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <div class="nav-collapse collapse">
                        <a class="brand">
                            <?php if ($this->brand['icon']): ?>
                            <i class="icon-<?php echo $this->escapeHtmlAttr($this->brand['icon']) ?> icon-white"></i>
                            <?php endif ?>
                            <?php echo $this->escapeHtml($this->brand['text']) ?>
                        </a>
                        <?php echo $this->navigation('navigation')->menu()
                                ->renderMenu(null, array(
                                    'ulClass' => 'nav'
                                )) ?>
                        <?php echo $this->navigation('infinityuser_navigation')->menu()
                                ->renderMenu(null, array(
                                    'ulClass' => 'nav pull-right'
                                )) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <?php echo $this->messages() ?>
            <div class="row-fluid">
                <?php echo $this->content ?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>